name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: submodules
      run : |
        git submodule update --init --recursive
        sudo apt install lcov

    - name: Build
      run: cmake -H. -B _build -DCOVERAGE=1  && cmake --build _build

    - name: Test
      working-directory: ${{github.workspace}}/_build

      run: |
        ./test
        lcov -c -t "test" -o lcov.info -d .
        lcov --remove lcov.info '/home/runner/work/lab05/lab05/third-party/gtest/' -o lcov.info
        lcov --remove lcov.info '/usr/include/' -o lcov.info

    - name: CovBeg
      uses: coverallsapp/github-action@master
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./_build/lcov.info
          coveralls-endpoint: https://coveralls.io/
